name: CI Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MESSAGE: "Hola desde variable"

    steps:
      - uses: actions/checkout@v3

      - name: Print variable
        run: echo $MESSAGE