name: CI Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MESSAGE: "Hola desde variable"

    steps:
      - uses: actions/checkout@v3

      - name: Print variable
        run: echo $MESSAGE

      - name: Run test
        run: cat test.txt

      - name: Upload file
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: my-file
          path: test.txt